name: gigafile_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  cookie_jar: ^4.0.8
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  freezed_annotation: ^3.1.0
  html: ^0.15.6
  json_annotation: ^4.9.0
  path: ^1.9.1
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  lints: ^5.0.0
  test: ^1.24.0
